/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.losguachines.Ordenador;

/**
 *
 * @author administrador
 */
public class ComandaMesa extends javax.swing.JPanel {

    /**
     * Creates new form ComandaMesa
     */
    public ComandaMesa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_comandaMesa = new javax.swing.JPanel();
        sp_comanda = new javax.swing.JScrollPane();
        tabla_comanda = new javax.swing.JTable();
        lb_tituloComanda = new javax.swing.JLabel();
        bt_completarComanda = new javax.swing.JButton();

        sp_comanda.setRequestFocusEnabled(false);

        tabla_comanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        sp_comanda.setViewportView(tabla_comanda);

        lb_tituloComanda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tituloComanda.setText("jLabel1");

        bt_completarComanda.setText("jButton1");

        javax.swing.GroupLayout panel_comandaMesaLayout = new javax.swing.GroupLayout(panel_comandaMesa);
        panel_comandaMesa.setLayout(panel_comandaMesaLayout);
        panel_comandaMesaLayout.setHorizontalGroup(
            panel_comandaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_comanda, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
            .addComponent(lb_tituloComanda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_comandaMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_completarComanda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_comandaMesaLayout.setVerticalGroup(
            panel_comandaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_comandaMesaLayout.createSequentialGroup()
                .addComponent(lb_tituloComanda, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp_comanda, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_completarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_comandaMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_comandaMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_completarComanda;
    private javax.swing.JLabel lb_tituloComanda;
    private javax.swing.JPanel panel_comandaMesa;
    private javax.swing.JScrollPane sp_comanda;
    private javax.swing.JTable tabla_comanda;
    // End of variables declaration//GEN-END:variables
}
